### ISSUE TITLE
ValueError: invalid version number '4.6.1rc'

### ISSUE THREAD

**Issue by hoetzgit** [matthewwall/weewx-windy#15]
Problem if characters are included in the version number.

```
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__: Caught unrecoverable exception:
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****  invalid version number '4.6.1rc'
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****  Traceback (most recent call last):
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****    File "/home/weewx/bin/weewxd", line 147, in main
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 93, in __init__
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****      self.loadServices(config_dict)
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****    File "/home/weewx/bin/weewx/engine.py", line 161, in loadServices
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****      obj = weeutil.weeutil.get_object(svc)(self, config_dict)
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****    File "/home/weewx/bin/weeutil/weeutil.py", line 1149, in get_object
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****      mod = __import__(module)
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****    File "/home/weewx/bin/user/windy.py", line 60, in <module>
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****      if StrictVersion(weewx.__version__) < StrictVersion(REQUIRED_WEEWX):
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****    File "/usr/lib/python3.8/distutils/version.py", line 40, in __init__
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****      self.parse(vstring)
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****    File "/usr/lib/python3.8/distutils/version.py", line 137, in parse
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****      raise ValueError("invalid version number '%s'" % vstring)
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****  ValueError: invalid version number '4.6.1rc'
Feb  8 09:52:29 weewx03 weewx[509490] CRITICAL __main__:     ****  Exiting.
```

**Comment by hoetzgit** [comment]
Obsolete
